name: build docker

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-circolari-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './Server/flask'
        steps:
          - name: 'github actions'
            uses: actions/checkout@main

          - name: 'login ghcr'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'build image'
            run: |
              docker build . --file Dockerfile --tag ghcr.io/Luca2040/riassunto_circolari:latest ./Server/flask
              docker push ghcr.io/Luca2040/riassunto_circolari:latest

